### ISSUE TITLE
non-numeric argument to binary operator error

### ISSUE THREAD

**Issue by asifrim** [jeremymcrae/recessiveStats#1]
> hgnc ="DNAH14"
> chrom = "1"
> lof_lof = 5
> lof_func = 6
> probands = c("DDDP00000X", "DDDP00000Y", "DDDP00000Z")
> analyse_inherited_enrichment(hgnc, chrom, lof_lof, lof_func, probands)
extracting ddd frequencies
loading DDD vcfs for DNAH14
converting DDD genotypes
tallying DDD allele counts
1:225347187 is non-LoF ref allele G at last base of exon
1:225445820 is non-LoF ref allele G at last base of exon
1:225576193 is non-LoF ref allele G at last base of exon
Error in lof_func + biallelic_lof :
  non-numeric argument to binary operator

**Comment by asifrim** [comment]
passing a biallelic_func to the function works, it's just missing from the example in the README.

**Comment by jeremymcrae** [comment]
updated readme to for current function call
