### ISSUE TITLE
pre-computed exac allele frequencies for all genes

### ISSUE THREAD

**Issue by monkollek** [jeremymcrae/recessiveStats#2]
Firstly, thank you for sharing the code for others to use :o)

Quick question, would you happen to have all the exac allele frequencies pre-computed in a table also that you can share? This would dramatically speed up things, especially for genes like TTN.

Thanks!

**Comment by jeremymcrae** [comment]
Yes, I have these frequencies computed, I can put them in the repository, or send them to you if that's easier. Let me know which you prefer.

**Comment by monkollek** [comment]
Thanks! Can you please send?
